AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets necessary for schema registry

Parameters:
  bucketName:
    Type: String
    Description: s3 bucket name containing schemas

Resources:
  schemaRegistryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketName
      VersioningConfiguration:
        Status: Enabled

  schemaRegistryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref schemaRegistryBucket
      PolicyDocument:
        Statement:
          -
            Resource:
             - !GetAtt schemaRegistryBucket.Arn
             - !Join ['', [!GetAtt schemaRegistryBucket.Arn, '/*']]
            Effect: Allow
            Principal: '*'
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:PutObjectTagging
              - s3:PutObjectVersionAcl
              - s3:PutObjectVersionTagging
              - s3:RestoreObject

Outputs:
  schemaRegistryBucketArn:
    Value: !GetAtt schemaRegistryBucket.Arn
    Export:
      Name: !Join [-, [!Ref bucketName, bucket-arn]]